# Site settings
title: Levi McCallum
subtitle: Consumer Application Developer
email: levi@levimccallum.com
description: >
  The personal site of Levi McCallum, a California based iOS developer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://levimccallum.com" # the base hostname & protocol for your site
twitter_username: levi
github_username:  levi
linkedin_username:  levimccallum
ga_code: UA-56777852-1

# Build settings
markdown: kramdown

permalink: /carefullymade/:title.html

sass:
  style: :compressed

gems:
  - jemoji
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
