# Site settings
title: Levi McCallum
subtitle: Consumer Application Developer
email: levi@levimccallum.com
description: > # this means to ignore newlines until "baseurl:"
  The personal site of Levi McCallum, a California based consumer application developer for iOS and web apps.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://levi.so" # the base hostname & protocol for your site
twitter_username: levi
github_username:  levi
linkedin_username:  levimccallum

# Build settings
markdown: kramdown

permalink: /carefullymade/:title.html

sass:
  style: :compressed

gems:
  - jemoji
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
